# Generated by Django 3.0.5 on 2021-07-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_finalarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
